list-pokemon:
  handler: src/functions/pokemon/list.handler
  name: ${self:custom.dotenv.API_NAME}-list-pokemon
  description: Função para listar Pokemons
  memorySize: 128
  events:
    - http:
        path: /pokemon
        method: get
        cors: true

create-pokemon:
  handler: src/functions/pokemon/create.handler
  name: ${self:custom.dotenv.API_NAME}-create-pokemon
  description: Função para criar Pokemons
  memorySize: 128
  events:
    - http:
        path: /pokemon/create
        method: post
        cors: true


# update-pokemon:
#   handler: src/functions/pokemon/update.handler
#   name: ${self:custom.dotenv.API_NAME}-update-pokemon
#   description: Função para atualizar Pokemons
#   memorySize: 128
#   events:
#     - http:
#         path: /pokemon/update/{id}
#         method: put
#         cors: true      

# delete-pokemon:
#   handler: src/functions/pokemon/delete.handler
#   name: ${self:custom.dotenv.API_NAME}-delete-pokemon
#   description: Função para deletar um pokemon
#   memorySize: 128
#   events:
#     - http:
#         path: /pokemon/delete/{id}
#         method: delete
#         cors: true        